spring:
  application:
    name: itoken-service-sso
  boot:
    admin:
      client:
        url: http://123.207.49.252:8084
  zipkin:
    base-url: http://123.207.49.252:9411
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
  datasource:
    druid:
      url: jdbc:mysql://47.107.157.226:3306/itoken-service-admin?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      # MySQL 8.x: com.mysql.cj.jdbc.Driver
      driver-class-name: com.mysql.jdbc.Driver

feign:
  hystrix:
    enabled: true

server:
  port: 8501

mybatis:
    type-aliases-package: com.funtl.itoken.common.domain
    mapper-locations: classpath:mapper/*.xml

eureka:
  client:
    serviceUrl:
      defaultZone: http://123.207.49.252:8761/eureka/,http://123.207.49.252:8861/eureka/,http://123.207.49.252:8961/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info